version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: ./.env
    volumes:
      - ./summaries.db:/app/summaries.db          # persist the SQLite file
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"   # host:container
    depends_on:
      - backend
